### PR TITLE
[CLOUD-800] Update package dependencies for Ubuntu 22.04 AMI

### PR DESCRIPTION
**Pull request by willgraybeal**
https://actioniq.atlassian.net/browse/CLOUD-800

The ubuntu dependencies step for telegraf fails on ubuntu 22.04 due to packages not existing in the new OS. Updating the problematic packages to their 22.04 versions, conditional on the ansible_distribution_version being 22.04.
  - python-httplib2 --> python3-httplib2
  - python-apt --> python3-apt

Tested by building a 22.04 AMI in https://github.com/ActionIQ/aiq/pull/47025. Also verified that telegraf was running on a 22.04 devstack host 
image

Also tested building the existing 18.04 AMI successfully.

### CODE REVIEW

**Comment by willgraybeal** [comment]
The devops/cloud-eng groups don't exist for this github org, so I just added any devops members as reviewers.

**Review by cyrus-sig — COMMENTED** [review]
Can this affect current deployments?
i.e. If this is merged, will active deployments that are not yet using ubuntu22.04 attempt to pull in these changes since they will be on master branch?

**Comment by willgraybeal** [comment]
> Can this affect current deployments? i.e. If this is merged, will active deployments that are not yet using ubuntu22.04 attempt to pull in these changes since they will be on master branch?

It should not affect any current deployments since we only download the updated packages `if ansible_distribution_version == '22.04'`, which is not the case anywhere currently. I tested building an existing 18.04 AMI to verify.

**Review by cyrus-sig — APPROVED** [review]
LGTM!

**Pull request merged**
