### PR TITLE
Cloudwatch output for telegraf

### PR DESCRIPTION
**Pull request by MasterDDT**

### CODE REVIEW

**Comment by MasterDDT** [comment]
@casey-green @takism1 @mrwiggles so I got this working, I could use the existing influxCnxn and telegraf would send that to cloudwatch (with a `namepass`): https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#metricsV2:graph=~();namespace=mitesh_test_cloudwatch;dimensions=app_name,autoscale_group_name,customer_id,env,host,is_field_user,prod,user_id

 However I realized telegraf has a flush interval of 5mins or some number of points, that is not good enough for my purposes. I need the metric to show up every 15s in order to quickly autoscale.

So Im gonna close this and have the AIQ code talk directly to cloudwatch metrics

**Comment by casey-green** [comment]
can you change the flush interval? it would be great if we could just use all of our existing metrics infrastructure to do this.

**Comment by MasterDDT** [comment]
I didnt see a way to do it per-output, it was a global setting: https://github.com/ActionIQ-OSS/telegraf/blob/master/templates/telegraf.conf.j2#L43

I guess...we could have 2 telegrafs up? One that is maybe low SLA, one high SLA.

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/ActionIQ-OSS/telegraf">ActionIQ-OSS/telegraf</a></strong></div><div>telegraf - Ansible role for installing, configuring, and maintaining Telegraf</div></blockquote>

**Comment by casey-green** [comment]
Do you really need 15-second intervals? I don't think you want your autoscaling rules firing every 15 seconds anyways.

Can we reduce it globally to say 1 minute? I think its probably OK for a job to sit queued for 1 minute in the io cluster every once in awhile.

**Comment by MasterDDT** [comment]
No dont need 15s intervals, but also I'm worried telegraf can even do a 1 min sla. The farrrrrr majority of stuff on it is "lets analyze this over the last few hours/days/weeks" so its hard to claim its gonna work.

I dont care too much, easy to switch to using this since I already figure out the plugin. More just worried about flexibility of telegraf because its got a lot of global configs instead of per-output configs. Also note i was flitering this metric out of prom since didnt wanna add the extra load there, so what this was really saving me was ~10 lines of AWS metric code.

**Comment by casey-green** [comment]
> I'm worried telegraf can even do a 1 min sla.

I'm curious why you think this. I don't think we've actually ever had issues with telegraf itself, right @mrwiggles ? It's a pretty simple component.

> what this was really saving me was ~10 lines of AWS metric code.

I think it saves us some tech debt as well since we are leveraging some of our existing infrastructure to solve a new problem, and not adding some new hook.

**Comment by MasterDDT** [comment]
We dont do anything in telegraf that requires 1min latency right? Most granular I see is 5m: https://github.com/ActionIQ/aiq/blob/5f457d84f5e6015527a452c6a404f20a42c52283/deploy/kube/configs/prometheus/config.yml#L28

I can use it here, but I would be surprised if we uncover bugs in it due to this new load, and I can fix them as we go. But that means the SLA of autoscale is not dp+cloudwatch services having to be up, its dp+telegraf+cloudwatch now. I suppose its worth the extra cost in this feature, because we want telegraf to be more robust anyways. 

<blockquote><div><strong><a href="https://github.com/ActionIQ/aiq/blob/5f457d84f5e6015527a452c6a404f20a42c52283/deploy/kube/configs/prometheus/config.yml#L28">Page not found · GitHub</a></strong></div></blockquote>

**Pull request closed without merging**
